Sesame update
NCI-GDC/gdc-docs pull request #126
Opened 2021-08-06 19:46 UTC by bullenc

2021-08-30 17:29 UTC, wwysoc2 requested changes
@bullenc could you put the Harmonization Workflow at the top and the Liftover section at the bottom?

2021-08-30 17:32 UTC, bullenc commented
> @bullenc could you put the Harmonization Workflow at the top and the Liftover section at the bottom?

Will do!

2021-08-30 21:18 UTC, bullenc commented
Ok, the sections have been switched around

2021-09-10 19:12 UTC, wwysoc2 approved these changes

2021-09-10 19:12 UTC, merged