DOC-425 part 4: FM Simple Somatic Mutation, FoundationOne Annotation and FoundationOne Variant Aggregation and Masking
NCI-GDC/gdc-docs pull request #358
Opened 2024-06-05 20:24 UTC by ebusygina

Drafts for FM Simple Somatic Mutation, FoundationOne Annotation and FoundationOne Variant Aggregation and Masking workflows. I'm less sure about these workflows as they don't have that much info.

2024-07-12 20:01 UTC, wwysoc2 requested changes

2024-07-12 20:01 UTC, wwysoc2 commented on docs/Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md
> +FoundationOne Variant Aggregation and Masking is a pipeline used for targeted sequencing somatic mutation aggregation at the GDC. Somatic mutation aggregation is performed with FoundationOne Variant
```suggestion
FoundationOne Variant Aggregation and Masking is a pipeline used for targeted sequencing somatic mutation aggregation at the GDC. Somatic mutation aggregation is performed by aggregating annotated somatic mutations from the FM-AD project in the GDC by case primary site.
```

2024-07-12 20:01 UTC, wwysoc2 commented on docs/Encyclopedia/pages/FoundationOne_Annotation.md
> +## References ##
```suggestion
```

2024-07-12 20:01 UTC, wwysoc2 commented on docs/Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md
> +1. []()
```suggestion
```

2024-07-15 18:59 UTC, ebusygina commented on docs/Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
> +FM (Foundation Medicine) Simple Somatic Mutation (SSM) workflow is a genomic profile harmonization workflow in the GDC for identifying simple somatic mutations in targeted sequencing data.
changed

2024-07-15 19:00 UTC, ebusygina commented on docs/Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
> +FM Simple Somatic Mutation is one of the pipelines used for genomic profile harmonization at the GDC. Genomic profile harmonization is performed with FM Simple Somatic Mutation using tumor alignments
changed

2024-07-15 19:00 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Annotation.md
> +FoundationOne Annotation is a pipeline used for targeted sequencing somatic mutation annotation at the GDC. Somatic mutation annotation is performed with FoundationOne Annotation using tumor alignmen
changed

2024-07-15 19:00 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Annotation.md
> +1. []()
deleted

2024-07-15 19:00 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Annotation.md
> +1. []()
deleted

2024-07-15 19:00 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md
> +FoundationOne Variant Aggregation and Masking is a pipeline used for targeted sequencing somatic mutation aggregation at the GDC. Somatic mutation aggregation is performed with FoundationOne Variant
changed

2024-07-15 19:01 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Annotation.md
> +## References ##
deleted

2024-07-15 19:01 UTC, ebusygina commented on docs/Encyclopedia/pages/FoundationOne_Variant_Aggregation_and_Masking.md
> +1. []()
deleted

2024-07-19 20:34 UTC, wwysoc2 approved these changes
There's one change I requested (I must have missed it before).  So feel free to merge after you do that.

2024-07-19 20:34 UTC, wwysoc2 commented on docs/Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
> +* Submitted sequencing reads
```suggestion
* Submitted genomic profiles
```

2024-07-22 17:35 UTC, ebusygina commented on docs/Encyclopedia/pages/FM_Simple_Somatic_Mutation.md
> +* Submitted sequencing reads
changed

2024-07-22 17:42 UTC, merged