DOC-425 part 6: Pindel, Pindel Annotation, SeSAMe Methylation Beta Estimation, Seurat - 10x Chromium, STAR - Counts, STAR 2-Pass Chimeric, STAR 2-Pass Genome, STAR 2-Pass Transcriptome, STAR-Fusion
NCI-GDC/gdc-docs pull request #364
Opened 2024-06-21 15:43 UTC by ebusygina

Drafts for Pindel, Pindel Annotation, SeSAMe Methylation Beta Estimation, Seurat - 10x Chromium, STAR - Counts, STAR 2-Pass Chimeric, STAR 2-Pass Genome, STAR 2-Pass Transcriptome, STAR-Fusion workflows

2024-07-12 19:48 UTC, wwysoc2 requested changes

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Pindel.md
> +Pindel is one of the pipelines used for WGS, WXS and targeted sequencing somatic variant calling at the GDC. Somatic variant calling is performed with Pindel using tumor and normal alignments and gen
```suggestion
Pindel is one of the pipelines used for WGS, WXS and targeted sequencing somatic variant calling at the GDC. Somatic variant calling is performed with Pindel using tumor and normal alignments and generates indel data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +Pindel Annotation is a pipeline used for WXS and targeted sequencing somatic mutation annotation at the GDC. Somatic mutation annotation is performed with Pindel Annotation using tumor and normal ali
```suggestion
Pindel Annotation is a pipeline used for WXS and targeted sequencing somatic mutation annotation at the GDC. Somatic mutation annotation is performed by annotating raw VCFs, which produces annotated somatic mutation files.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +* Tumor VCF - WXS or Targeted Sequencing
```suggestion
* Raw VCF - WXS or Targeted Sequencing
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +* Normal VCF - WXS or Targeted Sequencing
```suggestion
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +* Tumor BAM - RNA-Seq
```suggestion
* BAM - RNA-Seq
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +* Normal BAM - RNA-Seq
```suggestion
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +STAR-Fusion is a pipeline used for RNA-Seq structural variant calling at the GDC. Structural variant calling is performed with STAR-Fusion using tumor and normal alignments and generates structural v
```suggestion
STAR-Fusion is a pipeline used for RNA-Seq structural variant calling at the GDC. Structural variant calling is performed with STAR-Fusion using tumor or normal alignments and generates structural variation data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_2-Pass_Chimeric.md
> +STAR 2-Pass Chimeric is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Chimeric using tumor and normal alignments and generates sequencing reads data.
```suggestion
STAR 2-Pass Chimeric is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR and generates sequencing reads data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_2-Pass_Genome.md
> +STAR 2-Pass Genome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Genome using tumor and normal alignments and generates sequencing reads data.
```suggestion
STAR 2-Pass Genome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR and generates sequencing reads data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_2-Pass_Transcriptome.md
> +STAR 2-Pass Transcriptome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Transcriptome using tumor and normal alignments and generates sequencing r
```suggestion
STAR 2-Pass Transcriptome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR and generates sequencing reads data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_Counts.md
> +STAR - Counts is a pipeline used for to quantify RNA gene and exon expression from unharmonized or GDC harmonized data. Quantification is performed with STAR - Counts using tumor and normal alignment
```suggestion
STAR - Counts is a pipeline used for to quantify gene expression from RNA-Seq data. Quantification is performed with STAR using tumor or normal alignments and generates transcriptome profiling data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_Counts.md
> +* Tumor BAM - RNA-Seq
```suggestion
* Genomic BAM - RNA-Seq
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/STAR_Counts.md
> +* Normal BAM - RNA-Seq
```suggestion
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/SeSAMe_Methylation_Beta_Estimation.md
> +SeSAMe Methylation Beta Estimation is the only pipeline used for methylation array harmonization at the GDC. Methylation array harmonization is performed with SeSAMe Methylation Beta Estimation using
```suggestion
SeSAMe Methylation Beta Estimation is used for methylation array harmonization at the GDC. Methylation array harmonization is performed with SeSAMe using raw tumor or normal methylation array files and generates beta values and masked intensities data, which removes potential genotype information.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Seurat_10x_Chromium.md
> +Seurat - 10x Chromium is a pipeline used for scRNA-Seq for secondary gene expression analysis at the GDC. Secondary gene expression analysis is performed with Seurat - 10x Chromium using tumor alignm
```suggestion
Seurat - 10x Chromium is a pipeline used for scRNA-Seq for secondary gene expression analysis at the GDC. Secondary gene expression analysis is performed with Seurat using gene expression data and generates transcriptome profiling data.
```

2024-07-12 19:48 UTC, wwysoc2 commented on docs/Encyclopedia/pages/Seurat_10x_Chromium.md
> +* Tumor MEX - scRNA-Seq
```suggestion
* MEX (Filtered Counts) - scRNA-Seq
```

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/Pindel.md
> +Pindel is one of the pipelines used for WGS, WXS and targeted sequencing somatic variant calling at the GDC. Somatic variant calling is performed with Pindel using tumor and normal alignments and gen
changed

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +Pindel Annotation is a pipeline used for WXS and targeted sequencing somatic mutation annotation at the GDC. Somatic mutation annotation is performed with Pindel Annotation using tumor and normal ali
changed

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +* Tumor VCF - WXS or Targeted Sequencing
changed

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/Pindel_Annotation.md
> +* Normal VCF - WXS or Targeted Sequencing
deleted

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +* Tumor BAM - RNA-Seq
changed

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +* Normal BAM - RNA-Seq
deleted

2024-07-15 18:04 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR-Fusion.md
> +STAR-Fusion is a pipeline used for RNA-Seq structural variant calling at the GDC. Structural variant calling is performed with STAR-Fusion using tumor and normal alignments and generates structural v
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR_2-Pass_Chimeric.md
> +STAR 2-Pass Chimeric is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Chimeric using tumor and normal alignments and generates sequencing reads data.
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR_2-Pass_Genome.md
> +STAR 2-Pass Genome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Genome using tumor and normal alignments and generates sequencing reads data.
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR_2-Pass_Transcriptome.md
> +STAR 2-Pass Transcriptome is a pipeline used for RNA-Seq reads alignment at the GDC. Alignment is performed with STAR 2-Pass Transcriptome using tumor and normal alignments and generates sequencing r
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR_Counts.md
> +STAR - Counts is a pipeline used for to quantify RNA gene and exon expression from unharmonized or GDC harmonized data. Quantification is performed with STAR - Counts using tumor and normal alignment
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/STAR_Counts.md
> +* Tumor BAM - RNA-Seq
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/SeSAMe_Methylation_Beta_Estimation.md
> +SeSAMe Methylation Beta Estimation is the only pipeline used for methylation array harmonization at the GDC. Methylation array harmonization is performed with SeSAMe Methylation Beta Estimation using
changed

2024-07-15 18:05 UTC, ebusygina commented on docs/Encyclopedia/pages/Seurat_10x_Chromium.md
> +Seurat - 10x Chromium is a pipeline used for scRNA-Seq for secondary gene expression analysis at the GDC. Secondary gene expression analysis is performed with Seurat - 10x Chromium using tumor alignm
changed

2024-07-15 18:06 UTC, ebusygina commented on docs/Encyclopedia/pages/Seurat_10x_Chromium.md
> +* Tumor MEX - scRNA-Seq
changed

2024-07-19 20:45 UTC, wwysoc2 approved these changes
LGTM 👍

2024-07-22 17:56 UTC, merged