adds SJ's release notes and a UC known issue, some reorganization
NCI-GDC/gdc-docs pull request #420
Opened 2024-10-24 04:54 UTC by wteouchicago

- added SJ's release notes
- added a UC known issue
- some reorganization

2024-10-24 05:08 UTC, wteouchicago commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> -* In __Gene Expression Clustering__, the tooltip is not displayed when clicking an expression data cell.
i moved these upwards

2024-10-24 05:11 UTC, wteouchicago commented
@siosonel - FYI, I made minor edits for consistency; merged the 508 ones into one row. Also, I left out the general item about preventing the cache from being stale since that's not something user-facing -- let me know if you think I should add it.

2024-10-24 14:31 UTC, siosonel commented
> @siosonel - FYI, I made minor edits for consistency; merged the 508 ones into one row. Also, I left out the general item about preventing the cache from being stale since that's not something user-facing -- let me know if you think I should add it.

@wteouchicago that should be okay. We will commit a few other minor fixes to our release notes today.

2024-10-24 14:46 UTC, wwysoc2 requested changes

2024-10-24 14:46 UTC, clsackett reviewed
1 small change, otherwise LGTM

2024-10-24 14:46 UTC, wwysoc2 commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * Users can now change the plot color scheme to Blue-White-Red, Blue-White-Red, Green-Black-Red, Green-Black-Red, and Blue-Black-Yellow, under the Clustering tab.
```suggestion
    * Users can now change the plot color scheme to Blue-White-Red, Green-Black-Red, Green-Black-Red, and Blue-Black-Yellow, under the Clustering tab.
```

2024-10-24 14:46 UTC, wwysoc2 commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * Fixed gene search results latency when pressing Enter key immediately, to prevent showing invalid search error message.
```suggestion
    * Fixed gene search results latency when pressing the Enter key immediately, to prevent showing invalid search error message.
```

2024-10-24 14:46 UTC, clsackett commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * In table listing available BAM files, replace outdated sample_type variable with tissue_type and tumor_descriptor.
I think "replace" --> "replaced"

2024-10-24 14:55 UTC, wteouchicago commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * In table listing available BAM files, replace outdated sample_type variable with tissue_type and tumor_descriptor.
for sure!

2024-10-24 14:56 UTC, wteouchicago commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * There is a computation error when the the first genes in a gene expression data request does not have data for any sample.
I'll check. @siosonel may know too.

2024-10-24 15:16 UTC, wteouchicago commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * There is a computation error when the the first genes in a gene expression data request does not have data for any sample.
from testing, it looks like it happens when it's literally the first gene. I'll update.

2024-10-24 15:27 UTC, clsackett approved these changes

2024-10-24 16:29 UTC, siosonel commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * There is a computation error when the the first genes in a gene expression data request does not have data for any sample.
I'll fix the wording, may take up to an hour. Please let me know if it's more urgent, I could rush it.

2024-10-24 16:34 UTC, wteouchicago commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * There is a computation error when the the first genes in a gene expression data request does not have data for any sample.
@siosonel no problem -- I think by sometime tomorrow is fine.

2024-10-24 17:24 UTC, siosonel commented on docs/Data_Portal/Release_Notes/Data_Portal_Release_Notes.md
> +    * There is a computation error when the the first genes in a gene expression data request does not have data for any sample.
I'll take my time to make edits later this afternoon and evening, also to minimize conflicts as others are correcting or have already corrected some of the same lines that I might edit

2024-10-24 22:15 UTC, siosonel approved these changes

2024-10-25 20:38 UTC, wwysoc2 approved these changes
👍 lgtm

2024-10-26 01:24 UTC, merged